tasks:
  - init: npm install;
    command: npm run start;
# Ports to expose on workspace startup (optional)
ports:
  - port: 3000
    onOpen: open-preview
vscode:
  extensions:
    - ritwickdey.liveserver@5.6.1:e4c865d51815543708ca6d7adf1f2bfb